# Generated by Django 4.1.1 on 2023-06-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
